name: deploy-toy-website
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
jobs:
  say-hello:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken("set_by_owner")
            coredemo.setOutput('id_token', id_token)
      - name: Login huaweicloud
        run: |
          curl -H "Authorization: Bearer ${{steps.idtoken.outputs.id_token}}" https://iam.myhuaweicloud.com/v3/OS-FEDERATION/identity_providers/vjtest/protocols/oidc/auth -H "Accept: application/json;" -H "Content-Type: application/json" -d "{}"
      - name: List Versions of ECS With Default Region By KooCLI 
        uses: huaweicloud/huaweicloud-cli-action@v1.0.1
        with:
          commandList: 'hcloud ecs ListCloudServers --cli-region=ap-southeast-3'
